### ISSUE TITLE
AttributeError: 'ADAPI' object has no attribute 'timer_running'

### ISSUE THREAD

**Issue by Eeeeeediot** [Odianosen25/Monitor-App#78]
self.handle_echo(location=location, payload=payload)
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 548, in handle_echo
    if location in self.location_timers and self.adbase.timer_running(
AttributeError: 'ADAPI' object has no attribute 'timer_running'
2021-04-01 22:55:42.265367 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:55:45.921859 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:55:45.923442 WARNING home_presence_app: Unexpected error in worker for App home_presence_app:
2021-04-01 22:55:45.924456 WARNING home_presence_app: Worker Ags: {'id': 'bf9e29b03e3e45f297a056d2a14614d5', 'name': 'home_presence_app', 'objectid': 'b086503a69c945359ae0877a0a3ceeb0', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method HomePresenceApp.presence_message of <home_presence_app.HomePresenceApp object at 0x7f9e895a30>>, 'data': {'topic': 'monitor/living_room_monitor/status', 'payload': 'online', 'wildcard': 'monitor/#'}, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'wildcard': 'monitor/#', '__thread_id': 'thread-5'}}
2021-04-01 22:55:45.927698 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:55:45.931239 WARNING home_presence_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 933, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 280, in presence_message
    self.handle_status(location=location, payload=payload.lower())
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 472, in handle_status
    and self.adbase.timer_running(self.location_timers[location])
AttributeError: 'ADAPI' object has no attribute 'timer_running'
2021-04-01 22:55:45.932663 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:07.664033 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:07.665423 WARNING home_presence_app: Unexpected error in worker for App home_presence_app:
2021-04-01 22:56:07.666625 WARNING home_presence_app: Worker Ags: {'id': 'bf9e29b03e3e45f297a056d2a14614d5', 'name': 'home_presence_app', 'objectid': 'b086503a69c945359ae0877a0a3ceeb0', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method HomePresenceApp.presence_message of <home_presence_app.HomePresenceApp object at 0x7f9e895a30>>, 'data': {'topic': 'monitor/living_room_monitor/echo', 'payload': 'ok', 'wildcard': 'monitor/#'}, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'wildcard': 'monitor/#', '__thread_id': 'thread-5'}}
2021-04-01 22:56:07.668326 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:07.669895 WARNING home_presence_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 933, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 293, in presence_message
    self.handle_echo(location=location, payload=payload)
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 548, in handle_echo
    if location in self.location_timers and self.adbase.timer_running(
AttributeError: 'ADAPI' object has no attribute 'timer_running'
2021-04-01 22:56:07.671133 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:22.025568 INFO home_presence_app: Processing System Unavailable for Living Room Monitor
2021-04-01 22:56:22.514685 WARNING home_presence_app: Node at Living Room Monitor is Offline, will need to be checked
2021-04-01 22:56:37.253921 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:37.261544 WARNING home_presence_app: Unexpected error in worker for App home_presence_app:
2021-04-01 22:56:37.263291 WARNING home_presence_app: Worker Ags: {'id': '5c967c6d38d44d068b682ce108b47e5f', 'name': 'home_presence_app', 'objectid': 'b086503a69c945359ae0877a0a3ceeb0', 'type': 'scheduler', 'function': <bound method HomePresenceApp.not_home_func of <home_presence_app.HomePresenceApp object at 0x7f9e895a30>>, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'device_entity_id': 'monitor_stephen_phone', '__thread_id': 'thread-5'}}
2021-04-01 22:56:37.264376 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:37.270412 WARNING home_presence_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 887, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 777, in not_home_func
    if self.check_home_timer is not None and self.adbase.timer_running(
AttributeError: 'ADAPI' object has no attribute 'timer_running'
2021-04-01 22:56:37.271390 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:37.341508 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:37.347841 WARNING home_presence_app: Unexpected error in worker for App home_presence_app:
2021-04-01 22:56:37.349629 WARNING home_presence_app: Worker Ags: {'id': '215ba7050d8948e08b851bdc6fb28a6d', 'name': 'home_presence_app', 'objectid': 'b086503a69c945359ae0877a0a3ceeb0', 'type': 'scheduler', 'function': <bound method HomePresenceApp.not_home_func of <home_presence_app.HomePresenceApp object at 0x7f9e895a30>>, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'device_entity_id': 'monitor_april_phone', '__thread_id': 'thread-5'}}
2021-04-01 22:56:37.353619 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:37.355424 WARNING home_presence_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 887, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 777, in not_home_func
    if self.check_home_timer is not None and self.adbase.timer_running(
AttributeError: 'ADAPI' object has no attribute 'timer_running'
2021-04-01 22:56:37.356522 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:39.024138 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:39.025058 WARNING home_presence_app: Unexpected error in worker for App home_presence_app:
2021-04-01 22:56:39.025971 WARNING home_presence_app: Worker Ags: {'id': 'bf9e29b03e3e45f297a056d2a14614d5', 'name': 'home_presence_app', 'objectid': 'b086503a69c945359ae0877a0a3ceeb0', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method HomePresenceApp.presence_message of <home_presence_app.HomePresenceApp object at 0x7f9e895a30>>, 'data': {'topic': 'monitor/living_room_monitor/status', 'payload': 'online', 'wildcard': 'monitor/#'}, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'wildcard': 'monitor/#', '__thread_id': 'thread-5'}}
2021-04-01 22:56:39.026744 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:39.030293 WARNING home_presence_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 933, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 280, in presence_message
    self.handle_status(location=location, payload=payload.lower())
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 472, in handle_status
    and self.adbase.timer_running(self.location_timers[location])
AttributeError: 'ADAPI' object has no attribute 'timer_running'
2021-04-01 22:56:39.031121 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:41.026379 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:41.028377 WARNING home_presence_app: Unexpected error in worker for App home_presence_app:
2021-04-01 22:56:41.030157 WARNING home_presence_app: Worker Ags: {'id': 'bf9e29b03e3e45f297a056d2a14614d5', 'name': 'home_presence_app', 'objectid': 'b086503a69c945359ae0877a0a3ceeb0', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method HomePresenceApp.presence_message of <home_presence_app.HomePresenceApp object at 0x7f9e895a30>>, 'data': {'topic': 'monitor/living_room_monitor/status', 'payload': 'online', 'wildcard': 'monitor/#'}, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'wildcard': 'monitor/#', '__thread_id': 'thread-5'}}
2021-04-01 22:56:41.031404 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:41.033235 WARNING home_presence_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 933, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 280, in presence_message
    self.handle_status(location=location, payload=payload.lower())
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 472, in handle_status
    and self.adbase.timer_running(self.location_timers[location])
AttributeError: 'ADAPI' object has no attribute 'timer_running'
2021-04-01 22:56:41.035628 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:42.782597 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:42.783717 WARNING home_presence_app: Unexpected error in worker for App home_presence_app:
2021-04-01 22:56:42.784642 WARNING home_presence_app: Worker Ags: {'id': '3028589bc57a484590a6fc6859c9c507', 'name': 'home_presence_app', 'objectid': 'b086503a69c945359ae0877a0a3ceeb0', 'type': 'state', 'function': <bound method HomePresenceApp.confidence_updated of <home_presence_app.HomePresenceApp object at 0x7f9e895a30>>, 'attribute': 'state', 'entity': 'sensor.monitor_april_phone_living_room_monitor_conf', 'new_state': '100', 'old_state': '0', 'pin_app': True, 'pin_thread': 5, 'kwargs': {'device_entity_id': 'monitor_april_phone', 'immediate': True, '__duration': '41602fbf55ac4637bfb42ff54938ce44', '__thread_id': 'thread-5'}}
2021-04-01 22:56:42.785629 WARNING home_presence_app: ------------------------------------------------------------
2021-04-01 22:56:42.787055 WARNING home_presence_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 900, in worker
    funcref(
  File "/config/appdaemon/apps/Monitor-App/home_presence_app.py", line 701, in confidence_updated
    if self.check_home_timer is not None and self.adbase.timer_running(
AttributeError: 'ADAPI' object has no attribute 'timer_running'
2021-04-01 22:56:42.788028 WARNING home_presence_app: ------------------------------------------------------------

**Comment by Odianosen25** [comment]
Hello @Eeeeeediot,

You should be running AD 4.0.7 minimum. I need to add that to the docs

**Comment by Odianosen25** [comment]
I believe this should be fixed, so closing this issue
